# 텐서(TENSOR)
- 텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 NumPy의 ndnarray와 유사하다.

In [1]:
import torch
import numpy as np

# 텐서(tensor) 초기화

- 텐서는 여러가지 방법으로 초기화할 수 있다.
- **데이터로부터 직접(directly) 생성하기**
- 데이터로부터 직접 텐서를 생성할 수 있다. 데이터의 자료형(data type)은 자동으로 유추한다.

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

# tensor([[1, 2],
#         [3, 4]])

tensor([[1, 2],
        [3, 4]])

## NumPy 배열로부터 생성하기
- 텐서는 NumPy 배열로 생성할 수 있다.

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

# tensor([[1, 2],
#         [3, 4]], dtype=torch.int32)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

## 다른 텐서로부터 생성하기
- 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지한다.

In [5]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지한다.
print("Ones Tensor: \n {} \n".format(x_ones))

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print("Random Tensor: \n {} \n".format(x_rand))

# Ones Tensor: 
#  tensor([[1, 1],
#         [1, 1]]) 

# Random Tensor: 
#  tensor([[0.8170, 0.8521],
#         [0.9835, 0.6030]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8170, 0.8521],
        [0.9835, 0.6030]]) 



## 무작위(random) 또는 상수( constanct)값 사용하기
- shape은 텐서의 차원(dimension)을 나타내는 튜플(tuple)로, 아래 함수들에서는 출력 텐서의 차원을 결정한다.

In [6]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("Random Tensor: \n {} \n".format(rand_tensor))
print("Ones Tensor: \n {} \n".format(ones_tensor))
print("zeros Tensor: \n {} \n".format(zeros_tensor))

# Random Tensor: 
#  tensor([[0.2485, 0.6439, 0.5177],
#         [0.6080, 0.2484, 0.9851]]) 

# Ones Tensor: 
#  tensor([[1., 1., 1.],
#         [1., 1., 1.]]) 

# zeros Tensor: 
#  tensor([[0., 0., 0.],
#         [0., 0., 0.]]) 

Random Tensor: 
 tensor([[0.2485, 0.6439, 0.5177],
        [0.6080, 0.2484, 0.9851]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# 텐서의 속성(Attribute)
- 텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타낸다.

In [7]:
tensor = torch.rand(3, 4)

print("Shape of tensor : {}".format(tensor.shape))
print("Datatype of tensor : {}".format(tensor.dtype))
print("Device tensor is stored on : {}".format(tensor.device))

# Shape of tensor : torch.Size([3, 4])
# Datatype of tensor : torch.float32
# Device tensor is stored on : cpu

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


# 텐서 연산(Operation)
- 전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등 100가지 이상의 텐서 연산들을 [여기](https://pytorch.org/docs/stable/torch.html)에
서 확인할 수 있다.


- 각 연산들은(일반적으로 CPU보다 빠른) GPU에서 실행할 수 있다.


- 기본적으로 텐서는 CPU에 생성된다. `.to` 메소드를 사용하면(GPU의 가용성을 확인한 뒤) GPU로 텐서를 명시적으로 이동할 수 있다.
    - 장치들간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이 든다는 것을 기억해야 한다.

In [8]:
# GPU가 존재하면 텐서를 이동한다.
if torch.cuda.is_available():
    tensor = tenso.to('cuda')

- 목록에서 몇몇 연산들을 시도해보자. Numpy API에 익숙하다면 Tensor API를 사용하는 것은 식은 죽 먹기이다.
## Numpy식의 표준 인덱싱과 슬라이싱 :

In [9]:
tensor = torch.ones(4, 4)
print("First row: ", tensor[0])
print("First col: ", tensor[:, 0])
print("Last col: ", tensor[:, -1])
tensor[:, 1] = 0
print(tensor)

# First row:  tensor([1., 1., 1., 1.])
# First col:  tensor([1., 1., 1., 1.])
# Last col:  tensor([1., 1., 1., 1.])
# tensor([[1., 0., 1., 1.],
#         [1., 0., 1., 1.],
#         [1., 0., 1., 1.],
#         [1., 0., 1., 1.]])

First row:  tensor([1., 1., 1., 1.])
First col:  tensor([1., 1., 1., 1.])
Last col:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


- **텐서 합치기** => `torch.cat` 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있다.

`torch.cat`과 미묘하게 다른 또 다른 텐서 결합 연산인 `torch.stack`도 있다.

In [17]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


## 산술 연산(Arithmetic operations)

In [24]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산한다. y1, y2, y3은 모두 같은 값을 가진다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

# tensor([[3., 3., 3., 3.],
#         [3., 3., 3., 3.],
#         [3., 3., 3., 3.],
#         [3., 3., 3., 3.]])

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [25]:
# 요소별 곱(element-wise produt)을 계산한다. z1, z2, z2는 모두 같은 값을 가진다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

# tensor([[1., 0., 1., 1.],
#         [1., 0., 1., 1.],
#         [1., 0., 1., 1.],
#         [1., 0., 1., 1.]])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

- **단일-요소(single-element) 텐서** => 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, `item()`을 사용하여 Python 숫자 값으로 변환할 수 있다.

In [26]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

# 12.0 <class 'float'>

12.0 <class 'float'>


- **바꿔치기(in-place)연산** => 연산 결고를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며, `_` 접미사를 갖는다. 

예를 들어 : `x.copy_(y)` 나 `x.t_()` 는 `x`를 변경한다.

In [28]:
print(tensor, '\n')
tensor.add_(5)
print(tensor)

# tensor([[1., 0., 1., 1.],
#         [1., 0., 1., 1.],
#         [1., 0., 1., 1.],
#         [1., 0., 1., 1.]]) 

# tensor([[6., 5., 6., 6.],
#         [6., 5., 6., 6.],
#         [6., 5., 6., 6.],
#         [6., 5., 6., 6.]])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# NumPy 변환(Bridge)
- CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.
## 텐서를 NumPy 배열로 반환하기 

In [30]:
t = torch.ones(5)
print("t: {}".format(t))

n = t.numpy()
print("n: {}".format(n))

# t: tensor([1., 1., 1., 1., 1.])
# n: [1. 1. 1. 1. 1.]

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


- 텐서의 변경 사항이 NumPy 배열에 반영된다.

In [31]:
t.add_(1)
print("t: {}".format(t))
print("n: {}".format(n))

# t: tensor([2., 2., 2., 2., 2.])
# n: [2. 2. 2. 2. 2.]

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## NumPy 배열을 텐서로 변환하기

In [32]:
n = np.ones(5)
t = torch.from_numpy(n)

- NumPy 배열의 변경 사항이 텐서에 반영된다.

In [33]:
np.add(n, 1, out = n)

print("t: {}".format(t))
print("n: {}".format(n))

# t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
# n: [2. 2. 2. 2. 2.]

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
